version: '3'

services:
  keycloak:
    image: keycloak/keycloak:25.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    volumes:
      - ./keycloak-db:/opt/keycloak/data
    ports:
      - "8080:8080"

  oidc-sandbox:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
