import keycloak
from keycloak.uma_permissions import UMAPermission


keycloak_open_id_connection = keycloak.KeycloakOpenIDConnection(
    server_url="http://localhost:8080",
    realm_name="meetup",
    client_id="backend",
    client_secret_key="ZD7fYF7yFlzoouf2rH65P6PqJzhWx2pN"
)

keycloak_uma = keycloak.KeycloakUMA(
    connection=keycloak_open_id_connection
)

access_token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGYm9IOHZRSnBXdEtOWjAtUnRya1dkdHFkZVZGUUwzd2tKazN3bExTU0lBIn0.eyJleHAiOjE3MjcxMDYzMTEsImlhdCI6MTcyNzEwNjAxMSwiYXV0aF90aW1lIjoxNzI3MDk3OTk3LCJqdGkiOiIxNGJmNzA5MC00ODQyLTQ0MGYtOTVhNC1iNjQwMzI4OTdmM2MiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21lZXR1cCIsImF1ZCI6WyJiYWNrZW5kIiwiYWNjb3VudCJdLCJzdWIiOiI1Njk5NWNmYi1mYzhmLTRjZDUtOWIyMC1kMzg4NmQ5YmZiMGUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvaWRjLXNhbmRib3giLCJzaWQiOiI2NTEzOGM1ZC01ZWY4LTQwNWEtOTBkZi1jZDgwY2M0MzM1NjUiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1tZWV0dXAiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYmFja2VuZCI6eyJyb2xlcyI6WyJmaW5vcHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZ3JvdXBzIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ1c2VyMSB1c2VyMSIsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXIxIiwiZ2l2ZW5fbmFtZSI6InVzZXIxIiwiZmFtaWx5X25hbWUiOiJ1c2VyMSIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20ifQ.nWttaVQ0U2CGNqDwMMR9hetVF0rm9aC3fjmqyiGKzgQTCStLPt6PoSBO7QV6Qx8wpD7mBdrT4Q4PpxKdGSIxaS0eDFiUByhbOpmfvDNQAq58l9e02GYAESKIBbfF6Ci0PGBLYJMDgb6DnmFofLnBXcI2U4zCEt0DJGKOvWjIzIOh86gGpRNuRe3pUMn0HBJqfrk3oaMsgSdW30vFwmEY_t1MnCtP7UK9bvPacY7A0R7W4wpw-1GNo4qxUv-lEQP4E6_No86VPzZAaWrL48VYQYP3ih0Tm3ZAdFnpzdSDC4YwQzcGKf1lOPeS3qXywkABb8WoeS-oDtN5y56qn2ZW6Q"


cloud_billing_data_permission = UMAPermission(resource="cloud_billing_data")
sales_data_permission = UMAPermission(resource="sales_data")

print(keycloak_uma.permissions_check(token=access_token, permissions=[cloud_billing_data_permission]))
print(keycloak_uma.permissions_check(token=access_token, permissions=[sales_data_permission]))
